// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/banshee_api.dart';
import 'api/run_api.dart';
import 'api/simple.dart';
import 'api/stats_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1376690559;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'banshee_run',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<double> crateApiRunApiAddPointToRun({
    required String runId,
    required GpsPointDto point,
  });

  double crateApiStatsApiCalculateDistance({
    required double lat1,
    required double lon1,
    required double lat2,
    required double lon2,
  });

  BansheeStateDto crateApiBansheeApiCalculateBansheeDelta({
    required double bansheeDistanceM,
    required PlatformInt64 bansheeTimeMs,
    required double runnerDistanceM,
    required PlatformInt64 runnerTimeMs,
    double? targetPaceSecPerKm,
  });

  double crateApiStatsApiCalculatePace({
    required double distanceM,
    required PlatformInt64 durationMs,
  });

  double crateApiStatsApiCalculatePacePerMile({
    required double distanceM,
    required PlatformInt64 durationMs,
  });

  double crateApiStatsApiCalculateTotalDistance({
    required List<(double, double)> points,
  });

  int crateApiBansheeApiCheckPositionChange({
    required double previousDeltaM,
    required double currentDeltaM,
    required double thresholdM,
  });

  Future<String> crateApiRunApiCreateRun();

  Future<bool> crateApiRunApiDeleteRun({required String id});

  double crateApiStatsApiEstimateCalories({
    required double weightKg,
    required double distanceM,
  });

  PlatformInt64? crateApiStatsApiEstimateFinishTime({
    required double targetDistanceM,
    required double currentDistanceM,
    required PlatformInt64 currentDurationMs,
  });

  Future<RunDetailDto> crateApiRunApiFinishRun({required String runId});

  String crateApiStatsApiFormatDistanceKm({required double distanceM});

  String crateApiStatsApiFormatDistanceMiles({required double distanceM});

  String crateApiStatsApiFormatDuration({required PlatformInt64 durationMs});

  String crateApiBansheeApiFormatBansheeDelta({
    required double distanceDeltaMeters,
  });

  String crateApiStatsApiFormatPace({required double paceSecPerKm});

  String crateApiStatsApiFormatPacePerMile({required double paceSecPerKm});

  Future<BansheeStateDto> crateApiBansheeApiGetAiPacerPosition({
    required double startLat,
    required double startLon,
    required double targetPaceSecPerKm,
    required PlatformInt64 elapsedMs,
    List<(double, double)>? route,
  });

  Future<List<RunSummaryDto>> crateApiRunApiGetAllRuns();

  List<(double, String)> crateApiBansheeApiGetPacePresets();

  Future<BansheeStateDto> crateApiBansheeApiGetRecordedBansheePosition({
    required String runId,
    required PlatformInt64 elapsedMs,
  });

  Future<RunDetailDto?> crateApiRunApiGetRun({required String id});

  Future<PlatformInt64> crateApiRunApiGetRunCount();

  Future<double> crateApiRunApiGetTotalDistance();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiRunApiInitDatabase({required String dbPath});

  double crateApiStatsApiPaceToSpeed({required double paceSecPerKm});

  double crateApiStatsApiProjectDistanceAtTime({
    required double currentDistanceM,
    required PlatformInt64 currentDurationMs,
    required PlatformInt64 targetDurationMs,
  });

  Future<void> crateApiRunApiSaveRun({required RunDto runDto});

  double crateApiStatsApiSpeedToPace({required double speedMps});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<double> crateApiRunApiAddPointToRun({
    required String runId,
    required GpsPointDto point,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(runId, serializer);
          sse_encode_box_autoadd_gps_point_dto(point, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiAddPointToRunConstMeta,
        argValues: [runId, point],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiAddPointToRunConstMeta =>
      const TaskConstMeta(
        debugName: "add_point_to_run",
        argNames: ["runId", "point"],
      );

  @override
  double crateApiStatsApiCalculateDistance({
    required double lat1,
    required double lon1,
    required double lat2,
    required double lon2,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(lat1, serializer);
          sse_encode_f_64(lon1, serializer);
          sse_encode_f_64(lat2, serializer);
          sse_encode_f_64(lon2, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiCalculateDistanceConstMeta,
        argValues: [lat1, lon1, lat2, lon2],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiCalculateDistanceConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_distance",
        argNames: ["lat1", "lon1", "lat2", "lon2"],
      );

  @override
  BansheeStateDto crateApiBansheeApiCalculateBansheeDelta({
    required double bansheeDistanceM,
    required PlatformInt64 bansheeTimeMs,
    required double runnerDistanceM,
    required PlatformInt64 runnerTimeMs,
    double? targetPaceSecPerKm,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(bansheeDistanceM, serializer);
          sse_encode_i_64(bansheeTimeMs, serializer);
          sse_encode_f_64(runnerDistanceM, serializer);
          sse_encode_i_64(runnerTimeMs, serializer);
          sse_encode_opt_box_autoadd_f_64(targetPaceSecPerKm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_banshee_state_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBansheeApiCalculateBansheeDeltaConstMeta,
        argValues: [
          bansheeDistanceM,
          bansheeTimeMs,
          runnerDistanceM,
          runnerTimeMs,
          targetPaceSecPerKm,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBansheeApiCalculateBansheeDeltaConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_banshee_delta",
        argNames: [
          "bansheeDistanceM",
          "bansheeTimeMs",
          "runnerDistanceM",
          "runnerTimeMs",
          "targetPaceSecPerKm",
        ],
      );

  @override
  double crateApiStatsApiCalculatePace({
    required double distanceM,
    required PlatformInt64 durationMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(distanceM, serializer);
          sse_encode_i_64(durationMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiCalculatePaceConstMeta,
        argValues: [distanceM, durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiCalculatePaceConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_pace",
        argNames: ["distanceM", "durationMs"],
      );

  @override
  double crateApiStatsApiCalculatePacePerMile({
    required double distanceM,
    required PlatformInt64 durationMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(distanceM, serializer);
          sse_encode_i_64(durationMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiCalculatePacePerMileConstMeta,
        argValues: [distanceM, durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiCalculatePacePerMileConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_pace_per_mile",
        argNames: ["distanceM", "durationMs"],
      );

  @override
  double crateApiStatsApiCalculateTotalDistance({
    required List<(double, double)> points,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_record_f_64_f_64(points, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiCalculateTotalDistanceConstMeta,
        argValues: [points],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiCalculateTotalDistanceConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_total_distance",
        argNames: ["points"],
      );

  @override
  int crateApiBansheeApiCheckPositionChange({
    required double previousDeltaM,
    required double currentDeltaM,
    required double thresholdM,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(previousDeltaM, serializer);
          sse_encode_f_64(currentDeltaM, serializer);
          sse_encode_f_64(thresholdM, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBansheeApiCheckPositionChangeConstMeta,
        argValues: [previousDeltaM, currentDeltaM, thresholdM],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBansheeApiCheckPositionChangeConstMeta =>
      const TaskConstMeta(
        debugName: "check_position_change",
        argNames: ["previousDeltaM", "currentDeltaM", "thresholdM"],
      );

  @override
  Future<String> crateApiRunApiCreateRun() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiCreateRunConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiCreateRunConstMeta =>
      const TaskConstMeta(debugName: "create_run", argNames: []);

  @override
  Future<bool> crateApiRunApiDeleteRun({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiDeleteRunConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiDeleteRunConstMeta =>
      const TaskConstMeta(debugName: "delete_run", argNames: ["id"]);

  @override
  double crateApiStatsApiEstimateCalories({
    required double weightKg,
    required double distanceM,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(weightKg, serializer);
          sse_encode_f_64(distanceM, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiEstimateCaloriesConstMeta,
        argValues: [weightKg, distanceM],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiEstimateCaloriesConstMeta =>
      const TaskConstMeta(
        debugName: "estimate_calories",
        argNames: ["weightKg", "distanceM"],
      );

  @override
  PlatformInt64? crateApiStatsApiEstimateFinishTime({
    required double targetDistanceM,
    required double currentDistanceM,
    required PlatformInt64 currentDurationMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(targetDistanceM, serializer);
          sse_encode_f_64(currentDistanceM, serializer);
          sse_encode_i_64(currentDurationMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiEstimateFinishTimeConstMeta,
        argValues: [targetDistanceM, currentDistanceM, currentDurationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiEstimateFinishTimeConstMeta =>
      const TaskConstMeta(
        debugName: "estimate_finish_time",
        argNames: ["targetDistanceM", "currentDistanceM", "currentDurationMs"],
      );

  @override
  Future<RunDetailDto> crateApiRunApiFinishRun({required String runId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_run_detail_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiFinishRunConstMeta,
        argValues: [runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiFinishRunConstMeta =>
      const TaskConstMeta(debugName: "finish_run", argNames: ["runId"]);

  @override
  String crateApiStatsApiFormatDistanceKm({required double distanceM}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(distanceM, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiFormatDistanceKmConstMeta,
        argValues: [distanceM],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiFormatDistanceKmConstMeta =>
      const TaskConstMeta(
        debugName: "format_distance_km",
        argNames: ["distanceM"],
      );

  @override
  String crateApiStatsApiFormatDistanceMiles({required double distanceM}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(distanceM, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiFormatDistanceMilesConstMeta,
        argValues: [distanceM],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiFormatDistanceMilesConstMeta =>
      const TaskConstMeta(
        debugName: "format_distance_miles",
        argNames: ["distanceM"],
      );

  @override
  String crateApiStatsApiFormatDuration({required PlatformInt64 durationMs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(durationMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiFormatDurationConstMeta,
        argValues: [durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiFormatDurationConstMeta =>
      const TaskConstMeta(
        debugName: "format_duration",
        argNames: ["durationMs"],
      );

  @override
  String crateApiBansheeApiFormatBansheeDelta({
    required double distanceDeltaMeters,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(distanceDeltaMeters, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBansheeApiFormatBansheeDeltaConstMeta,
        argValues: [distanceDeltaMeters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBansheeApiFormatBansheeDeltaConstMeta =>
      const TaskConstMeta(
        debugName: "format_banshee_delta",
        argNames: ["distanceDeltaMeters"],
      );

  @override
  String crateApiStatsApiFormatPace({required double paceSecPerKm}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(paceSecPerKm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiFormatPaceConstMeta,
        argValues: [paceSecPerKm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiFormatPaceConstMeta =>
      const TaskConstMeta(debugName: "format_pace", argNames: ["paceSecPerKm"]);

  @override
  String crateApiStatsApiFormatPacePerMile({required double paceSecPerKm}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(paceSecPerKm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiFormatPacePerMileConstMeta,
        argValues: [paceSecPerKm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiFormatPacePerMileConstMeta =>
      const TaskConstMeta(
        debugName: "format_pace_per_mile",
        argNames: ["paceSecPerKm"],
      );

  @override
  Future<BansheeStateDto> crateApiBansheeApiGetAiPacerPosition({
    required double startLat,
    required double startLon,
    required double targetPaceSecPerKm,
    required PlatformInt64 elapsedMs,
    List<(double, double)>? route,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(startLat, serializer);
          sse_encode_f_64(startLon, serializer);
          sse_encode_f_64(targetPaceSecPerKm, serializer);
          sse_encode_i_64(elapsedMs, serializer);
          sse_encode_opt_list_record_f_64_f_64(route, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_banshee_state_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBansheeApiGetAiPacerPositionConstMeta,
        argValues: [startLat, startLon, targetPaceSecPerKm, elapsedMs, route],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBansheeApiGetAiPacerPositionConstMeta =>
      const TaskConstMeta(
        debugName: "get_ai_pacer_position",
        argNames: [
          "startLat",
          "startLon",
          "targetPaceSecPerKm",
          "elapsedMs",
          "route",
        ],
      );

  @override
  Future<List<RunSummaryDto>> crateApiRunApiGetAllRuns() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_run_summary_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiGetAllRunsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiGetAllRunsConstMeta =>
      const TaskConstMeta(debugName: "get_all_runs", argNames: []);

  @override
  List<(double, String)> crateApiBansheeApiGetPacePresets() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_f_64_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBansheeApiGetPacePresetsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBansheeApiGetPacePresetsConstMeta =>
      const TaskConstMeta(debugName: "get_pace_presets", argNames: []);

  @override
  Future<BansheeStateDto> crateApiBansheeApiGetRecordedBansheePosition({
    required String runId,
    required PlatformInt64 elapsedMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(runId, serializer);
          sse_encode_i_64(elapsedMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_banshee_state_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBansheeApiGetRecordedBansheePositionConstMeta,
        argValues: [runId, elapsedMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBansheeApiGetRecordedBansheePositionConstMeta =>
      const TaskConstMeta(
        debugName: "get_recorded_banshee_position",
        argNames: ["runId", "elapsedMs"],
      );

  @override
  Future<RunDetailDto?> crateApiRunApiGetRun({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_run_detail_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiGetRunConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiGetRunConstMeta =>
      const TaskConstMeta(debugName: "get_run", argNames: ["id"]);

  @override
  Future<PlatformInt64> crateApiRunApiGetRunCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiGetRunCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiGetRunCountConstMeta =>
      const TaskConstMeta(debugName: "get_run_count", argNames: []);

  @override
  Future<double> crateApiRunApiGetTotalDistance() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiGetTotalDistanceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiGetTotalDistanceConstMeta =>
      const TaskConstMeta(debugName: "get_total_distance", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiRunApiInitDatabase({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiInitDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiInitDatabaseConstMeta =>
      const TaskConstMeta(debugName: "init_database", argNames: ["dbPath"]);

  @override
  double crateApiStatsApiPaceToSpeed({required double paceSecPerKm}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(paceSecPerKm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiPaceToSpeedConstMeta,
        argValues: [paceSecPerKm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiPaceToSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "pace_to_speed",
        argNames: ["paceSecPerKm"],
      );

  @override
  double crateApiStatsApiProjectDistanceAtTime({
    required double currentDistanceM,
    required PlatformInt64 currentDurationMs,
    required PlatformInt64 targetDurationMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(currentDistanceM, serializer);
          sse_encode_i_64(currentDurationMs, serializer);
          sse_encode_i_64(targetDurationMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiProjectDistanceAtTimeConstMeta,
        argValues: [currentDistanceM, currentDurationMs, targetDurationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiProjectDistanceAtTimeConstMeta =>
      const TaskConstMeta(
        debugName: "project_distance_at_time",
        argNames: ["currentDistanceM", "currentDurationMs", "targetDurationMs"],
      );

  @override
  Future<void> crateApiRunApiSaveRun({required RunDto runDto}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_run_dto(runDto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRunApiSaveRunConstMeta,
        argValues: [runDto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRunApiSaveRunConstMeta =>
      const TaskConstMeta(debugName: "save_run", argNames: ["runDto"]);

  @override
  double crateApiStatsApiSpeedToPace({required double speedMps}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(speedMps, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStatsApiSpeedToPaceConstMeta,
        argValues: [speedMps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStatsApiSpeedToPaceConstMeta =>
      const TaskConstMeta(debugName: "speed_to_pace", argNames: ["speedMps"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GpsPointDto dco_decode_box_autoadd_gps_point_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gps_point_dto(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  RunDetailDto dco_decode_box_autoadd_run_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_run_detail_dto(raw);
  }

  @protected
  RunDto dco_decode_box_autoadd_run_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_run_dto(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  BansheeStateDto dco_decode_banshee_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BansheeStateDto(
      lat: dco_decode_f_64(arr[0]),
      lon: dco_decode_f_64(arr[1]),
      distanceMeters: dco_decode_f_64(arr[2]),
      timeDeltaMs: dco_decode_i_64(arr[3]),
      distanceDeltaMeters: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  GpsPointDto dco_decode_gps_point_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return GpsPointDto(
      lat: dco_decode_f_64(arr[0]),
      lon: dco_decode_f_64(arr[1]),
      altitude: dco_decode_opt_box_autoadd_f_64(arr[2]),
      timestampMs: dco_decode_i_64(arr[3]),
      accuracy: dco_decode_opt_box_autoadd_f_64(arr[4]),
      speed: dco_decode_opt_box_autoadd_f_64(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<GpsPointDto> dco_decode_list_gps_point_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gps_point_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(double, double)> dco_decode_list_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_f_64_f_64).toList();
  }

  @protected
  List<(double, String)> dco_decode_list_record_f_64_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_f_64_string).toList();
  }

  @protected
  List<RunSummaryDto> dco_decode_list_run_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_run_summary_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  RunDetailDto? dco_decode_opt_box_autoadd_run_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_run_detail_dto(raw);
  }

  @protected
  List<(double, double)>? dco_decode_opt_list_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_record_f_64_f_64(raw);
  }

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_64(arr[0]), dco_decode_f_64(arr[1]));
  }

  @protected
  (double, String) dco_decode_record_f_64_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_64(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  RunDetailDto dco_decode_run_detail_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RunDetailDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      startTimeMs: dco_decode_i_64(arr[2]),
      endTimeMs: dco_decode_opt_box_autoadd_i_64(arr[3]),
      points: dco_decode_list_gps_point_dto(arr[4]),
      distanceMeters: dco_decode_f_64(arr[5]),
      durationMs: dco_decode_i_64(arr[6]),
      avgPaceSecPerKm: dco_decode_opt_box_autoadd_f_64(arr[7]),
    );
  }

  @protected
  RunDto dco_decode_run_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RunDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      startTimeMs: dco_decode_i_64(arr[2]),
      endTimeMs: dco_decode_opt_box_autoadd_i_64(arr[3]),
      points: dco_decode_list_gps_point_dto(arr[4]),
      distanceMeters: dco_decode_f_64(arr[5]),
      durationMs: dco_decode_i_64(arr[6]),
      avgPaceSecPerKm: dco_decode_opt_box_autoadd_f_64(arr[7]),
    );
  }

  @protected
  RunSummaryDto dco_decode_run_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RunSummaryDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      startTimeMs: dco_decode_i_64(arr[2]),
      distanceMeters: dco_decode_f_64(arr[3]),
      durationMs: dco_decode_i_64(arr[4]),
      avgPaceSecPerKm: dco_decode_opt_box_autoadd_f_64(arr[5]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  GpsPointDto sse_decode_box_autoadd_gps_point_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gps_point_dto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  RunDetailDto sse_decode_box_autoadd_run_detail_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_run_detail_dto(deserializer));
  }

  @protected
  RunDto sse_decode_box_autoadd_run_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_run_dto(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  BansheeStateDto sse_decode_banshee_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    var var_distanceMeters = sse_decode_f_64(deserializer);
    var var_timeDeltaMs = sse_decode_i_64(deserializer);
    var var_distanceDeltaMeters = sse_decode_f_64(deserializer);
    return BansheeStateDto(
      lat: var_lat,
      lon: var_lon,
      distanceMeters: var_distanceMeters,
      timeDeltaMs: var_timeDeltaMs,
      distanceDeltaMeters: var_distanceDeltaMeters,
    );
  }

  @protected
  GpsPointDto sse_decode_gps_point_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    var var_altitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    var var_accuracy = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_speed = sse_decode_opt_box_autoadd_f_64(deserializer);
    return GpsPointDto(
      lat: var_lat,
      lon: var_lon,
      altitude: var_altitude,
      timestampMs: var_timestampMs,
      accuracy: var_accuracy,
      speed: var_speed,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<GpsPointDto> sse_decode_list_gps_point_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GpsPointDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gps_point_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(double, double)> sse_decode_list_record_f_64_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(double, double)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_f_64_f_64(deserializer));
    }
    return ans_;
  }

  @protected
  List<(double, String)> sse_decode_list_record_f_64_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(double, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_f_64_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<RunSummaryDto> sse_decode_list_run_summary_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RunSummaryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_run_summary_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RunDetailDto? sse_decode_opt_box_autoadd_run_detail_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_run_detail_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<(double, double)>? sse_decode_opt_list_record_f_64_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_record_f_64_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (double, String) sse_decode_record_f_64_string(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RunDetailDto sse_decode_run_detail_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_startTimeMs = sse_decode_i_64(deserializer);
    var var_endTimeMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_points = sse_decode_list_gps_point_dto(deserializer);
    var var_distanceMeters = sse_decode_f_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_avgPaceSecPerKm = sse_decode_opt_box_autoadd_f_64(deserializer);
    return RunDetailDto(
      id: var_id,
      name: var_name,
      startTimeMs: var_startTimeMs,
      endTimeMs: var_endTimeMs,
      points: var_points,
      distanceMeters: var_distanceMeters,
      durationMs: var_durationMs,
      avgPaceSecPerKm: var_avgPaceSecPerKm,
    );
  }

  @protected
  RunDto sse_decode_run_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_startTimeMs = sse_decode_i_64(deserializer);
    var var_endTimeMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_points = sse_decode_list_gps_point_dto(deserializer);
    var var_distanceMeters = sse_decode_f_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_avgPaceSecPerKm = sse_decode_opt_box_autoadd_f_64(deserializer);
    return RunDto(
      id: var_id,
      name: var_name,
      startTimeMs: var_startTimeMs,
      endTimeMs: var_endTimeMs,
      points: var_points,
      distanceMeters: var_distanceMeters,
      durationMs: var_durationMs,
      avgPaceSecPerKm: var_avgPaceSecPerKm,
    );
  }

  @protected
  RunSummaryDto sse_decode_run_summary_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_startTimeMs = sse_decode_i_64(deserializer);
    var var_distanceMeters = sse_decode_f_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_avgPaceSecPerKm = sse_decode_opt_box_autoadd_f_64(deserializer);
    return RunSummaryDto(
      id: var_id,
      name: var_name,
      startTimeMs: var_startTimeMs,
      distanceMeters: var_distanceMeters,
      durationMs: var_durationMs,
      avgPaceSecPerKm: var_avgPaceSecPerKm,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gps_point_dto(
    GpsPointDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gps_point_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_run_detail_dto(
    RunDetailDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_run_detail_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_run_dto(RunDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_run_dto(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_banshee_state_dto(
    BansheeStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
    sse_encode_f_64(self.distanceMeters, serializer);
    sse_encode_i_64(self.timeDeltaMs, serializer);
    sse_encode_f_64(self.distanceDeltaMeters, serializer);
  }

  @protected
  void sse_encode_gps_point_dto(GpsPointDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
    sse_encode_opt_box_autoadd_f_64(self.altitude, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.accuracy, serializer);
    sse_encode_opt_box_autoadd_f_64(self.speed, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_gps_point_dto(
    List<GpsPointDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gps_point_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_f_64_f_64(
    List<(double, double)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_f_64_f_64(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_f_64_string(
    List<(double, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_f_64_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_run_summary_dto(
    List<RunSummaryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_run_summary_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_run_detail_dto(
    RunDetailDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_run_detail_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_record_f_64_f_64(
    List<(double, double)>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_record_f_64_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
  }

  @protected
  void sse_encode_record_f_64_string(
    (double, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_run_detail_dto(RunDetailDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_i_64(self.startTimeMs, serializer);
    sse_encode_opt_box_autoadd_i_64(self.endTimeMs, serializer);
    sse_encode_list_gps_point_dto(self.points, serializer);
    sse_encode_f_64(self.distanceMeters, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.avgPaceSecPerKm, serializer);
  }

  @protected
  void sse_encode_run_dto(RunDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_i_64(self.startTimeMs, serializer);
    sse_encode_opt_box_autoadd_i_64(self.endTimeMs, serializer);
    sse_encode_list_gps_point_dto(self.points, serializer);
    sse_encode_f_64(self.distanceMeters, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.avgPaceSecPerKm, serializer);
  }

  @protected
  void sse_encode_run_summary_dto(
    RunSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_i_64(self.startTimeMs, serializer);
    sse_encode_f_64(self.distanceMeters, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.avgPaceSecPerKm, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
