// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/banshee_api.dart';
import 'api/run_api.dart';
import 'api/simple.dart';
import 'api/stats_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GpsPointDto dco_decode_box_autoadd_gps_point_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  RunDetailDto dco_decode_box_autoadd_run_detail_dto(dynamic raw);

  @protected
  RunDto dco_decode_box_autoadd_run_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  BansheeStateDto dco_decode_banshee_state_dto(dynamic raw);

  @protected
  GpsPointDto dco_decode_gps_point_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<GpsPointDto> dco_decode_list_gps_point_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(double, double)> dco_decode_list_record_f_64_f_64(dynamic raw);

  @protected
  List<(double, String)> dco_decode_list_record_f_64_string(dynamic raw);

  @protected
  List<RunSummaryDto> dco_decode_list_run_summary_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RunDetailDto? dco_decode_opt_box_autoadd_run_detail_dto(dynamic raw);

  @protected
  List<(double, double)>? dco_decode_opt_list_record_f_64_f_64(dynamic raw);

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw);

  @protected
  (double, String) dco_decode_record_f_64_string(dynamic raw);

  @protected
  RunDetailDto dco_decode_run_detail_dto(dynamic raw);

  @protected
  RunDto dco_decode_run_dto(dynamic raw);

  @protected
  RunSummaryDto dco_decode_run_summary_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GpsPointDto sse_decode_box_autoadd_gps_point_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RunDetailDto sse_decode_box_autoadd_run_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  RunDto sse_decode_box_autoadd_run_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  BansheeStateDto sse_decode_banshee_state_dto(SseDeserializer deserializer);

  @protected
  GpsPointDto sse_decode_gps_point_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<GpsPointDto> sse_decode_list_gps_point_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(double, double)> sse_decode_list_record_f_64_f_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(double, String)> sse_decode_list_record_f_64_string(
    SseDeserializer deserializer,
  );

  @protected
  List<RunSummaryDto> sse_decode_list_run_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RunDetailDto? sse_decode_opt_box_autoadd_run_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<(double, double)>? sse_decode_opt_list_record_f_64_f_64(
    SseDeserializer deserializer,
  );

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer);

  @protected
  (double, String) sse_decode_record_f_64_string(SseDeserializer deserializer);

  @protected
  RunDetailDto sse_decode_run_detail_dto(SseDeserializer deserializer);

  @protected
  RunDto sse_decode_run_dto(SseDeserializer deserializer);

  @protected
  RunSummaryDto sse_decode_run_summary_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gps_point_dto(
    GpsPointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_run_detail_dto(
    RunDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_run_dto(RunDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_banshee_state_dto(
    BansheeStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gps_point_dto(GpsPointDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_gps_point_dto(
    List<GpsPointDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_f_64_f_64(
    List<(double, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_f_64_string(
    List<(double, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_run_summary_dto(
    List<RunSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_run_detail_dto(
    RunDetailDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_record_f_64_f_64(
    List<(double, double)>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_64_string(
    (double, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_run_detail_dto(RunDetailDto self, SseSerializer serializer);

  @protected
  void sse_encode_run_dto(RunDto self, SseSerializer serializer);

  @protected
  void sse_encode_run_summary_dto(RunSummaryDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
