// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_db`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`

/// Initialize the database with the given path
Future<void> initDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiRunApiInitDatabase(dbPath: dbPath);

/// Create a new run and return its ID
Future<String> createRun() => RustLib.instance.api.crateApiRunApiCreateRun();

/// Save a run (creates or updates)
Future<void> saveRun({required RunDto runDto}) =>
    RustLib.instance.api.crateApiRunApiSaveRun(runDto: runDto);

/// Get a run by ID
Future<RunDetailDto?> getRun({required String id}) =>
    RustLib.instance.api.crateApiRunApiGetRun(id: id);

/// Get all runs (summaries only)
Future<List<RunSummaryDto>> getAllRuns() =>
    RustLib.instance.api.crateApiRunApiGetAllRuns();

/// Delete a run by ID
Future<bool> deleteRun({required String id}) =>
    RustLib.instance.api.crateApiRunApiDeleteRun(id: id);

/// Get total run count
Future<PlatformInt64> getRunCount() =>
    RustLib.instance.api.crateApiRunApiGetRunCount();

/// Get total distance across all runs (in meters)
Future<double> getTotalDistance() =>
    RustLib.instance.api.crateApiRunApiGetTotalDistance();

/// Add a GPS point to a run and return updated distance
Future<double> addPointToRun({
  required String runId,
  required GpsPointDto point,
}) => RustLib.instance.api.crateApiRunApiAddPointToRun(
  runId: runId,
  point: point,
);

/// Finish a run
Future<RunDetailDto> finishRun({required String runId}) =>
    RustLib.instance.api.crateApiRunApiFinishRun(runId: runId);

/// DTO for creating a GPS point from Flutter
class GpsPointDto {
  final double lat;
  final double lon;
  final double? altitude;
  final PlatformInt64 timestampMs;
  final double? accuracy;
  final double? speed;

  const GpsPointDto({
    required this.lat,
    required this.lon,
    this.altitude,
    required this.timestampMs,
    this.accuracy,
    this.speed,
  });

  @override
  int get hashCode =>
      lat.hashCode ^
      lon.hashCode ^
      altitude.hashCode ^
      timestampMs.hashCode ^
      accuracy.hashCode ^
      speed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpsPointDto &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lon == other.lon &&
          altitude == other.altitude &&
          timestampMs == other.timestampMs &&
          accuracy == other.accuracy &&
          speed == other.speed;
}

/// DTO for returning full run to Flutter
class RunDetailDto {
  final String id;
  final String? name;
  final PlatformInt64 startTimeMs;
  final PlatformInt64? endTimeMs;
  final List<GpsPointDto> points;
  final double distanceMeters;
  final PlatformInt64 durationMs;
  final double? avgPaceSecPerKm;

  const RunDetailDto({
    required this.id,
    this.name,
    required this.startTimeMs,
    this.endTimeMs,
    required this.points,
    required this.distanceMeters,
    required this.durationMs,
    this.avgPaceSecPerKm,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      startTimeMs.hashCode ^
      endTimeMs.hashCode ^
      points.hashCode ^
      distanceMeters.hashCode ^
      durationMs.hashCode ^
      avgPaceSecPerKm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          startTimeMs == other.startTimeMs &&
          endTimeMs == other.endTimeMs &&
          points == other.points &&
          distanceMeters == other.distanceMeters &&
          durationMs == other.durationMs &&
          avgPaceSecPerKm == other.avgPaceSecPerKm;
}

/// DTO for run data from Flutter
class RunDto {
  final String id;
  final String? name;
  final PlatformInt64 startTimeMs;
  final PlatformInt64? endTimeMs;
  final List<GpsPointDto> points;
  final double distanceMeters;
  final PlatformInt64 durationMs;
  final double? avgPaceSecPerKm;

  const RunDto({
    required this.id,
    this.name,
    required this.startTimeMs,
    this.endTimeMs,
    required this.points,
    required this.distanceMeters,
    required this.durationMs,
    this.avgPaceSecPerKm,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      startTimeMs.hashCode ^
      endTimeMs.hashCode ^
      points.hashCode ^
      distanceMeters.hashCode ^
      durationMs.hashCode ^
      avgPaceSecPerKm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          startTimeMs == other.startTimeMs &&
          endTimeMs == other.endTimeMs &&
          points == other.points &&
          distanceMeters == other.distanceMeters &&
          durationMs == other.durationMs &&
          avgPaceSecPerKm == other.avgPaceSecPerKm;
}

/// DTO for returning run summary to Flutter
class RunSummaryDto {
  final String id;
  final String? name;
  final PlatformInt64 startTimeMs;
  final double distanceMeters;
  final PlatformInt64 durationMs;
  final double? avgPaceSecPerKm;

  const RunSummaryDto({
    required this.id,
    this.name,
    required this.startTimeMs,
    required this.distanceMeters,
    required this.durationMs,
    this.avgPaceSecPerKm,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      startTimeMs.hashCode ^
      distanceMeters.hashCode ^
      durationMs.hashCode ^
      avgPaceSecPerKm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          startTimeMs == other.startTimeMs &&
          distanceMeters == other.distanceMeters &&
          durationMs == other.durationMs &&
          avgPaceSecPerKm == other.avgPaceSecPerKm;
}
