// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SplitDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Calculate distance between two GPS points
double calculateDistance({
  required double lat1,
  required double lon1,
  required double lat2,
  required double lon2,
}) => RustLib.instance.api.crateApiStatsApiCalculateDistance(
  lat1: lat1,
  lon1: lon1,
  lat2: lat2,
  lon2: lon2,
);

/// Calculate total distance from a list of GPS points
double calculateTotalDistance({required List<(double, double)> points}) =>
    RustLib.instance.api.crateApiStatsApiCalculateTotalDistance(points: points);

/// Calculate pace from distance (meters) and duration (milliseconds)
/// Returns pace in seconds per kilometer
double calculatePace({
  required double distanceM,
  required PlatformInt64 durationMs,
}) => RustLib.instance.api.crateApiStatsApiCalculatePace(
  distanceM: distanceM,
  durationMs: durationMs,
);

/// Calculate pace per mile from distance (meters) and duration (milliseconds)
double calculatePacePerMile({
  required double distanceM,
  required PlatformInt64 durationMs,
}) => RustLib.instance.api.crateApiStatsApiCalculatePacePerMile(
  distanceM: distanceM,
  durationMs: durationMs,
);

/// Format pace (seconds per km) as MM:SS string
String formatPace({required double paceSecPerKm}) =>
    RustLib.instance.api.crateApiStatsApiFormatPace(paceSecPerKm: paceSecPerKm);

/// Format pace for miles
String formatPacePerMile({required double paceSecPerKm}) => RustLib.instance.api
    .crateApiStatsApiFormatPacePerMile(paceSecPerKm: paceSecPerKm);

/// Convert speed (m/s) to pace (sec/km)
double speedToPace({required double speedMps}) =>
    RustLib.instance.api.crateApiStatsApiSpeedToPace(speedMps: speedMps);

/// Convert pace (sec/km) to speed (m/s)
double paceToSpeed({required double paceSecPerKm}) => RustLib.instance.api
    .crateApiStatsApiPaceToSpeed(paceSecPerKm: paceSecPerKm);

/// Format duration (milliseconds) as HH:MM:SS or MM:SS
String formatDuration({required PlatformInt64 durationMs}) =>
    RustLib.instance.api.crateApiStatsApiFormatDuration(durationMs: durationMs);

/// Format distance in meters to a human-readable string
String formatDistanceKm({required double distanceM}) =>
    RustLib.instance.api.crateApiStatsApiFormatDistanceKm(distanceM: distanceM);

/// Format distance in meters to miles
String formatDistanceMiles({required double distanceM}) => RustLib.instance.api
    .crateApiStatsApiFormatDistanceMiles(distanceM: distanceM);

/// Calculate estimated finish time based on current pace
/// target_distance_m: target distance in meters
/// current_distance_m: current distance covered in meters
/// current_duration_ms: current duration in milliseconds
PlatformInt64? estimateFinishTime({
  required double targetDistanceM,
  required double currentDistanceM,
  required PlatformInt64 currentDurationMs,
}) => RustLib.instance.api.crateApiStatsApiEstimateFinishTime(
  targetDistanceM: targetDistanceM,
  currentDistanceM: currentDistanceM,
  currentDurationMs: currentDurationMs,
);

/// Calculate calories burned (rough estimate)
/// weight_kg: runner's weight in kilograms
/// distance_m: distance covered in meters
/// Uses MET value of ~10 for running
double estimateCalories({
  required double weightKg,
  required double distanceM,
}) => RustLib.instance.api.crateApiStatsApiEstimateCalories(
  weightKg: weightKg,
  distanceM: distanceM,
);

/// Calculate projected distance at target time based on current pace
double projectDistanceAtTime({
  required double currentDistanceM,
  required PlatformInt64 currentDurationMs,
  required PlatformInt64 targetDurationMs,
}) => RustLib.instance.api.crateApiStatsApiProjectDistanceAtTime(
  currentDistanceM: currentDistanceM,
  currentDurationMs: currentDurationMs,
  targetDurationMs: targetDurationMs,
);
